#ifndef CRT_MATERIALS_H_
#define CRT_MATERIALS_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t CRT_MATERIALS_PACKAGE[];
}

#define CRT_MATERIALS_CRT_SCREEN_OFFSET 0
#define CRT_MATERIALS_CRT_SCREEN_SIZE 55356
#define CRT_MATERIALS_CRT_SCREEN_DATA (CRT_MATERIALS_PACKAGE + CRT_MATERIALS_CRT_SCREEN_OFFSET)

#define CRT_MATERIALS_CHASSIS_METAL_OFFSET 55356
#define CRT_MATERIALS_CHASSIS_METAL_SIZE 45252
#define CRT_MATERIALS_CHASSIS_METAL_DATA (CRT_MATERIALS_PACKAGE + CRT_MATERIALS_CHASSIS_METAL_OFFSET)

#define CRT_MATERIALS_READOUT_DISPLAY_OFFSET 100608
#define CRT_MATERIALS_READOUT_DISPLAY_SIZE 45452
#define CRT_MATERIALS_READOUT_DISPLAY_DATA (CRT_MATERIALS_PACKAGE + CRT_MATERIALS_READOUT_DISPLAY_OFFSET)

#endif
