#include "eatsbits/eatscript/transpiler.hpp"
#include "eatsbits/eatscript/lexer.hpp"
#include "eatsbits/eatscript/parser.hpp"
#include <sstream>

namespace eatsbits::eatscript {

std::string Transpiler::emitIndent() const {
    return std::string(indentLevel_ * 4, ' ');
}

std::string Transpiler::transpileSource(const std::string& source, const std::string& pluginId,
                                        const std::string& pluginName) {
    Lexer lexer(source);
    auto tokens = lexer.tokenize();
    Parser parser(std::move(tokens));
    auto prog = parser.parse();
    if (!prog) return "// Parsing failed\n";
    return transpile(*prog, pluginId, pluginName);
}

std::string Transpiler::transpile(const Program& program, const std::string& pluginId,
                                  const std::string& pluginName) {
    processBodyCode_.clear();

    // Scan for process function
    for (const auto& stmt : program.statements) {
        auto* func = dynamic_cast<FunctionDef*>(stmt.get());
        if (func && func->name == "process") {
            inProcessFunction_ = true;
            indentLevel_ = 2;
            for (const auto& s : func->body) {
                s->accept(this);
            }
            inProcessFunction_ = false;
        }
    }

    std::ostringstream ss;
    ss << "// Generated by Eatsbits Eatscript AOT Transpiler\n";
    ss << "#include \"eatsbits/abi/eats_plugin_abi.h\"\n";
    ss << "#include <cmath>\n";
    ss << "#include <numbers>\n";
    ss << "#include <algorithm>\n\n";

    ss << "struct PluginInstance_" << pluginId << " {\n";
    ss << "    double sampleRate{48000.0};\n";
    ss << "    float params[16]{};\n";
    ss << "    double currentFreq{440.0};\n";
    ss << "    uint8_t currentNote{69};\n";
    ss << "    uint64_t sampleCount{0};\n";
    ss << "    bool active{false};\n";
    ss << "};\n\n";

    ss << "extern \"C\" {\n\n";

    // create_instance
    ss << "static void* create_instance_" << pluginId << "(double sampleRate) {\n";
    ss << "    auto* inst = new PluginInstance_" << pluginId << "();\n";
    ss << "    inst->sampleRate = sampleRate;\n";
    ss << "    return inst;\n";
    ss << "}\n\n";

    // destroy_instance
    ss << "static void destroy_instance_" << pluginId << "(void* instance) {\n";
    ss << "    delete static_cast<PluginInstance_" << pluginId << "*>(instance);\n";
    ss << "}\n\n";

    // set_param
    ss << "static void set_param_" << pluginId << "(void* instance, uint32_t paramId, float value) {\n";
    ss << "    auto* inst = static_cast<PluginInstance_" << pluginId << "*>(instance);\n";
    ss << "    if (paramId < 16) inst->params[paramId] = value;\n";
    ss << "}\n\n";

    // note_on
    ss << "static void note_on_" << pluginId << "(void* instance, uint8_t pitch, float velocity) {\n";
    ss << "    auto* inst = static_cast<PluginInstance_" << pluginId << "*>(instance);\n";
    ss << "    inst->currentNote = pitch;\n";
    ss << "    inst->currentFreq = 440.0 * std::pow(2.0, (static_cast<double>(pitch) - 69.0) / 12.0);\n";
    ss << "    inst->sampleCount = 0;\n";
    ss << "    inst->active = true;\n";
    ss << "}\n\n";

    // note_off
    ss << "static void note_off_" << pluginId << "(void* instance, uint8_t pitch) {\n";
    ss << "    auto* inst = static_cast<PluginInstance_" << pluginId << "*>(instance);\n";
    ss << "    if (inst->currentNote == pitch) inst->active = false;\n";
    ss << "}\n\n";

    // process
    ss << "static void process_" << pluginId << "(void* instance, const EatsAudioBuffer* buffer) {\n";
    ss << "    auto* inst = static_cast<PluginInstance_" << pluginId << "*>(instance);\n";
    ss << "    if (!inst->active) return;\n";
    ss << "    float* outL = buffer->outputs[0];\n";
    ss << "    float* outR = (buffer->numChannels > 1) ? buffer->outputs[1] : outL;\n";
    ss << "    const double freq = inst->currentFreq;\n";
    ss << "    const double note = static_cast<double>(inst->currentNote);\n";
    ss << "    const double sampleRate = inst->sampleRate;\n\n";

    ss << "    for (uint32_t i = 0; i < buffer->numSamples; ++i) {\n";
    ss << "        const double time = static_cast<double>(inst->sampleCount++) / sampleRate;\n";
    ss << "        double sample = 0.0;\n";
    ss << processBodyCode_;
    ss << "        outL[i] += static_cast<float>(sample);\n";
    ss << "        outR[i] += static_cast<float>(sample);\n";
    ss << "    }\n";
    ss << "}\n\n";

    // Plugin Descriptor
    ss << "const EatsPluginDescriptor g_plugin_" << pluginId << " = {\n";
    ss << "    \"" << pluginId << "\",\n";
    ss << "    \"" << pluginName << "\",\n";
    ss << "    16,\n";
    ss << "    create_instance_" << pluginId << ",\n";
    ss << "    destroy_instance_" << pluginId << ",\n";
    ss << "    process_" << pluginId << ",\n";
    ss << "    set_param_" << pluginId << ",\n";
    ss << "    note_on_" << pluginId << ",\n";
    ss << "    note_off_" << pluginId << "\n";
    ss << "};\n\n";

    ss << "} // extern \"C\"\n";

    return ss.str();
}

void Transpiler::visit(NumberLiteral* node) {
    output_ += std::to_string(node->value);
}

void Transpiler::visit(StringLiteral* node) {
    output_ += "\"" + node->value + "\"";
}

void Transpiler::visit(BooleanLiteral* node) {
    output_ += node->value ? "true" : "false";
}

void Transpiler::visit(IdentifierExpr* node) {
    if (node->name == "pi") {
        output_ += "std::numbers::pi_v<double>";
    } else {
        output_ += node->name;
    }
}

void Transpiler::visit(MemberExpr* node) {
    auto* objId = dynamic_cast<IdentifierExpr*>(node->object.get());
    if (objId && objId->name == "math" && node->member == "pi") {
        output_ += "std::numbers::pi_v<double>";
    } else {
        node->object->accept(this);
        output_ += "." + node->member;
    }
}

void Transpiler::visit(BinaryExpr* node) {
    output_ += "(";
    node->left->accept(this);
    switch (node->op) {
        case TokenType::Plus: output_ += " + "; break;
        case TokenType::Minus: output_ += " - "; break;
        case TokenType::Multiply: output_ += " * "; break;
        case TokenType::Divide: output_ += " / "; break;
        case TokenType::Power:
            // Rewrite a ** b as std::pow(a, b)
            output_ = "std::pow(" + output_;
            node->right->accept(this);
            output_ += ")";
            return;
        default: output_ += " + "; break;
    }
    node->right->accept(this);
    output_ += ")";
}

void Transpiler::visit(UnaryExpr* node) {
    if (node->op == TokenType::Minus) output_ += "-";
    node->operand->accept(this);
}

void Transpiler::visit(CallExpr* node) {
    auto* mem = dynamic_cast<MemberExpr*>(node->callee.get());
    if (mem) {
        auto* objId = dynamic_cast<IdentifierExpr*>(mem->object.get());
        if (objId && objId->name == "math") {
            output_ += "std::" + mem->member + "(";
            for (size_t i = 0; i < node->args.size(); ++i) {
                if (i > 0) output_ += ", ";
                node->args[i]->accept(this);
            }
            output_ += ")";
            return;
        } else if (objId && objId->name == "params" && mem->member == "get") {
            output_ += "inst->params[0]";
            return;
        }
    }

    node->callee->accept(this);
    output_ += "(";
    for (size_t i = 0; i < node->args.size(); ++i) {
        if (i > 0) output_ += ", ";
        node->args[i]->accept(this);
    }
    output_ += ")";
}

void Transpiler::visit(ListLiteral* node) {
    if (!node->elements.empty()) {
        node->elements[0]->accept(this);
    }
}

void Transpiler::visit(DictLiteral* /*node*/) {}

void Transpiler::visit(ExprStmt* node) {
    output_.clear();
    node->expression->accept(this);
    processBodyCode_ += emitIndent() + output_ + ";\n";
}

void Transpiler::visit(AssignStmt* node) {
    output_.clear();
    node->value->accept(this);
    processBodyCode_ += emitIndent() + "double " + node->variableName + " = " + output_ + ";\n";
}

void Transpiler::visit(ReturnStmt* node) {
    output_.clear();
    if (node->value) {
        node->value->accept(this);
        processBodyCode_ += emitIndent() + "sample = " + output_ + ";\n";
    }
}

void Transpiler::visit(IfStmt* node) {
    output_.clear();
    node->condition->accept(this);
    processBodyCode_ += emitIndent() + "if (" + output_ + ") {\n";
    indentLevel_++;
    for (const auto& s : node->thenBranch) {
        s->accept(this);
    }
    indentLevel_--;
    processBodyCode_ += emitIndent() + "}\n";
}

void Transpiler::visit(FunctionDef* /*node*/) {}

} // namespace eatsbits::eatscript
