#include "eatsbits/project/eats_serializer.hpp"
#include "eatsbits/audio/graph/nodes/tb303_node.hpp"
#include "eatsbits/audio/graph/nodes/drum_kit_node.hpp"
#include "eatsbits/audio/graph/nodes/poly_synth_node.hpp"
#include "eatsbits/audio/graph/nodes/biquad_node.hpp"
#include "eatsbits/audio/graph/nodes/delay_node.hpp"
#include "eatsbits/audio/graph/nodes/gain_node.hpp"
#include "eatsbits/audio/graph/nodes/eatscript_node.hpp"
#include <sstream>
#include <iomanip>
#include <regex>
#include <map>

namespace eatsbits::project {

static std::string escapeStr(const std::string& str) {
    std::string out;
    for (char c : str) {
        if (c == '"') out += "\\\"";
        else if (c == '\\') out += "\\\\";
        else out += c;
    }
    return out;
}

bool EatsProjectSerializer::isEatsScriptFormat(const std::string& content) noexcept {
    if (content.find("eatsbeats.song") != std::string::npos) return true;
    if (content.find("# Eatsbeats Song File:") != std::string::npos) return true;
    if (content.find("return eatsbeats.song") != std::string::npos) return true;
    return false;
}

std::string EatsProjectSerializer::serialize(
    const audio::AudioGraph& graph,
    const sequencer::StepSequencer& sequencer,
    const std::string& title,
    double bpm,
    double swing) {

    std::ostringstream ss;
    ss << std::fixed << std::setprecision(2);

    ss << "# Eatsbeats Song File: \"" << escapeStr(title) << "\"\n";
    ss << "# Generated by Eatsbeats DAW\n\n";
    ss << "return eatsbeats.song {\n";
    ss << "  version = \"1.0\",\n";

    // Meta
    ss << "  meta = {\n";
    ss << "    title = \"" << escapeStr(title) << "\",\n";
    ss << "    bpm = " << bpm << ",\n";
    ss << "    swing = " << swing << ",\n";
    ss << "    masterVolume = 0.85,\n";
    ss << "    isSongMode = false,\n";
    ss << "    isLooping = false,\n";
    ss << "  },\n\n";

    // Graph
    if (graph.getNodeCount() > 0) {
        ss << "  graph = {\n";
        ss << "    outputNodeId = " << graph.getOutputNodeId() << ",\n";
        ss << "    nodes = {\n";
        for (const auto& [id, node] : graph.getNodes()) {
            if (!node) continue;
            ss << "      {\n";
            ss << "        id = " << id << ",\n";
            ss << "        name = \"" << escapeStr(node->getName()) << "\",\n";

            if (auto* tb = dynamic_cast<audio::Tb303Node*>(node.get())) {
                ss << "        type = \"tb303\",\n";
            } else if (auto* dk = dynamic_cast<audio::DrumKitNode*>(node.get())) {
                ss << "        type = \"drum_kit\",\n";
            } else if (auto* ps = dynamic_cast<audio::PolySynthNode*>(node.get())) {
                ss << "        type = \"poly_synth\",\n";
            } else if (auto* bq = dynamic_cast<audio::BiquadNode*>(node.get())) {
                ss << "        type = \"biquad\",\n";
            } else if (auto* dl = dynamic_cast<audio::DelayNode*>(node.get())) {
                ss << "        type = \"delay\",\n";
                ss << "        delayTimeMs = " << dl->getDelayTimeMs() << ",\n";
                ss << "        feedback = " << dl->getFeedback() << ",\n";
                ss << "        dryWet = " << dl->getDryWet() << ",\n";
            } else if (auto* gn = dynamic_cast<audio::GainNode*>(node.get())) {
                ss << "        type = \"gain\",\n";
                ss << "        volume = " << gn->getVolume() << ",\n";
                ss << "        pan = " << gn->getPan() << ",\n";
                ss << "        muted = " << (gn->isMuted() ? "true" : "false") << ",\n";
            } else if (auto* es = dynamic_cast<audio::EatscriptNode*>(node.get())) {
                ss << "        type = \"eatscript\",\n";
                ss << "        script = [[\n" << es->getScript() << "\n        ]],\n";
            } else {
                ss << "        type = \"generic\",\n";
            }
            ss << "      },\n";
        }
        ss << "    },\n";

        ss << "    connections = {\n";
        for (const auto& conn : graph.getConnections()) {
            ss << "      { srcNode = " << conn.srcNode << ", srcPort = " << conn.srcPort
               << ", dstNode = " << conn.dstNode << ", dstPort = " << conn.dstPort << " },\n";
        }
        ss << "    },\n";
        ss << "  },\n\n";
    }

    // Patterns
    ss << "  patterns = {\n";
    for (size_t p = 0; p < sequencer.getNumPatterns(); ++p) {
        const auto& pat = sequencer.getPattern(p);
        ss << "    {\n";
        ss << "      id = \"pat_" << p << "\",\n";
        ss << "      name = \"" << escapeStr(pat.name) << "\",\n";
        ss << "      lengthSteps = 16,\n";
        ss << "      tracks = {\n";

        for (size_t t = 0; t < pat.tracks.size(); ++t) {
            const auto& track = pat.tracks[t];
            ss << "        {\n";
            ss << "          id = \"trk_" << t << "\",\n";
            ss << "          name = \"" << escapeStr(track.getName()) << "\",\n";
            ss << "          targetNodeId = " << track.getTargetNodeId() << ",\n";
            ss << "          volume = 0.850,\n";
            ss << "          pan = 0.000,\n";
            ss << "          isMuted = " << (track.isMuted() ? "true" : "false") << ",\n";
            ss << "          isSoloed = " << (track.isSolo() ? "true" : "false") << ",\n";

            // Embed Eatscript code
            const std::string& code = track.getEatscriptCode();
            if (!code.empty()) {
                ss << "          eatScriptCode = [[\n" << code << "\n          ]],\n";
            }

            // Steps
            ss << "          steps = {\n";
            for (uint32_t s = 0; s < track.getNumSteps(); ++s) {
                const auto& step = track.getStep(s);
                if (!step.active) continue;

                ss << "            [" << (s + 1) << "] = { ";
                ss << "pitch = " << static_cast<int>(step.note) << ", ";
                ss << "velocity = " << std::setprecision(2) << step.velocity << ", ";
                ss << "isSlide = " << (step.slide ? "true" : "false") << ", ";
                ss << "isAccent = " << (step.accent ? "true" : "false") << " },\n";
            }
            ss << "          },\n";
            ss << "        },\n";
        }

        ss << "      }\n";
        ss << "    },\n";
    }
    ss << "  },\n";
    ss << "}\n";

    return ss.str();
}

bool EatsProjectSerializer::deserialize(
    const std::string& eatsScript,
    audio::AudioGraph& graph,
    sequencer::StepSequencer& sequencer,
    std::string& outTitle,
    double& outBpm,
    double& outSwing) {

    if (!isEatsScriptFormat(eatsScript)) {
        return false;
    }

    outTitle = "Untitled Song";
    outBpm = 135.0;
    outSwing = 0.50;

    std::map<uint32_t, audio::NodeId> oldToNewId;

    // Check for graph block
    size_t graphPos = eatsScript.find("graph = {");
    if (graphPos != std::string::npos) {
        graph.clear();

        // Output Node Id
        static const std::regex outNodeRegex(R"(outputNodeId\s*=\s*(\d+))");
        std::smatch outMatch;
        uint32_t targetOutputId = audio::INVALID_NODE_ID;
        if (std::regex_search(eatsScript, outMatch, outNodeRegex)) {
            targetOutputId = static_cast<uint32_t>(std::stoul(outMatch[1].str()));
        }

        // Nodes block
        size_t nodesStart = eatsScript.find("nodes = {", graphPos);
        size_t connsStart = eatsScript.find("connections = {", graphPos);
        if (nodesStart != std::string::npos && connsStart != std::string::npos) {
            std::string nodesChunk = eatsScript.substr(nodesStart, connsStart - nodesStart);
            static const std::regex nodeStartRegex(R"(id\s*=\s*(\d+))");
            std::sregex_iterator nit(nodesChunk.begin(), nodesChunk.end(), nodeStartRegex);
            std::sregex_iterator nEnd;
            std::vector<size_t> nOffsets;
            for (; nit != nEnd; ++nit) {
                nOffsets.push_back(nit->position());
            }

            for (size_t i = 0; i < nOffsets.size(); ++i) {
                size_t nStart = nOffsets[i];
                size_t nEndPos = (i + 1 < nOffsets.size()) ? nOffsets[i + 1] : nodesChunk.size();
                std::string nStr = nodesChunk.substr(nStart, nEndPos - nStart);

                uint32_t oldId = 0;
                std::smatch nm;
                if (std::regex_search(nStr, nm, nodeStartRegex)) {
                    oldId = static_cast<uint32_t>(std::stoul(nm[1].str()));
                }

                std::string nName = "Node";
                static const std::regex nNameRegex(R"(name\s*=\s*["']([^"']*)["'])");
                if (std::regex_search(nStr, nm, nNameRegex)) {
                    nName = nm[1].str();
                }

                std::string nType = "generic";
                static const std::regex nTypeRegex(R"(type\s*=\s*["']([^"']*)["'])");
                if (std::regex_search(nStr, nm, nTypeRegex)) {
                    nType = nm[1].str();
                }

                std::shared_ptr<audio::GraphNode> newNode;
                if (nType == "tb303") {
                    newNode = std::make_shared<audio::Tb303Node>(nName.empty() ? "TB303" : nName);
                } else if (nType == "drum_kit") {
                    newNode = std::make_shared<audio::DrumKitNode>(nName.empty() ? "DrumKit" : nName);
                } else if (nType == "poly_synth") {
                    newNode = std::make_shared<audio::PolySynthNode>(nName.empty() ? "PolySynth" : nName);
                } else if (nType == "biquad") {
                    newNode = std::make_shared<audio::BiquadNode>(nName.empty() ? "Filter" : nName);
                } else if (nType == "delay") {
                    auto dl = std::make_shared<audio::DelayNode>(nName.empty() ? "Delay" : nName);
                    static const std::regex dtRegex(R"(delayTimeMs\s*=\s*([\d\.]+))");
                    static const std::regex fbRegex(R"(feedback\s*=\s*([\d\.]+))");
                    static const std::regex dwRegex(R"(dryWet\s*=\s*([\d\.]+))");
                    if (std::regex_search(nStr, nm, dtRegex)) dl->setDelayTimeMs(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, fbRegex)) dl->setFeedback(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, dwRegex)) dl->setDryWet(std::stof(nm[1].str()));
                    newNode = dl;
                } else if (nType == "gain") {
                    auto gn = std::make_shared<audio::GainNode>(nName.empty() ? "Gain" : nName);
                    static const std::regex volRegex(R"(volume\s*=\s*([\d\.]+))");
                    static const std::regex panRegex(R"(pan\s*=\s*([-\d\.]+))");
                    static const std::regex muteRegex(R"(muted\s*=\s*(true|false))");
                    if (std::regex_search(nStr, nm, volRegex)) gn->setVolume(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, panRegex)) gn->setPan(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, muteRegex)) gn->setMute(nm[1].str() == "true");
                    newNode = gn;
                } else if (nType == "eatscript") {
                    auto es = std::make_shared<audio::EatscriptNode>(nName.empty() ? "Eatscript" : nName);
                    static const std::regex scriptRegex(R"(script\s*=\s*\[\[([\s\S]*?)\]\])");
                    if (std::regex_search(nStr, nm, scriptRegex)) {
                        std::string sc = nm[1].str();
                        size_t f = sc.find_first_not_of(" \t\r\n");
                        size_t l = sc.find_last_not_of(" \t\r\n");
                        if (f != std::string::npos && l != std::string::npos) {
                            es->setScript(sc.substr(f, l - f + 1));
                        }
                    }
                    newNode = es;
                }

                if (newNode) {
                    audio::NodeId newId = graph.addNode(newNode);
                    oldToNewId[oldId] = newId;
                }
            }
        }

        // Connections block
        if (connsStart != std::string::npos) {
            std::string connChunk = eatsScript.substr(connsStart);
            static const std::regex connRegex(R"(\{\s*srcNode\s*=\s*(\d+),\s*srcPort\s*=\s*(\d+),\s*dstNode\s*=\s*(\d+),\s*dstPort\s*=\s*(\d+)\s*\})");
            std::sregex_iterator cit(connChunk.begin(), connChunk.end(), connRegex);
            std::sregex_iterator cEnd;
            for (; cit != cEnd; ++cit) {
                uint32_t oldSrc = static_cast<uint32_t>(std::stoul((*cit)[1].str()));
                uint32_t srcPort = static_cast<uint32_t>(std::stoul((*cit)[2].str()));
                uint32_t oldDst = static_cast<uint32_t>(std::stoul((*cit)[3].str()));
                uint32_t dstPort = static_cast<uint32_t>(std::stoul((*cit)[4].str()));

                if (oldToNewId.count(oldSrc) && oldToNewId.count(oldDst)) {
                    graph.connect(oldToNewId[oldSrc], srcPort, oldToNewId[oldDst], dstPort);
                }
            }
        }

        if (targetOutputId != audio::INVALID_NODE_ID && oldToNewId.count(targetOutputId)) {
            graph.setOutputNode(oldToNewId[targetOutputId], 0);
        }

        // Ensure a valid output node exists
        if (graph.getOutputNodeId() == audio::INVALID_NODE_ID && graph.getNodeCount() > 0) {
            audio::NodeId fallbackOut = audio::INVALID_NODE_ID;
            for (const auto& [id, node] : graph.getNodes()) {
                if (node && node->getName() == "MasterOut") {
                    fallbackOut = id;
                    break;
                }
            }
            if (fallbackOut == audio::INVALID_NODE_ID) {
                for (const auto& [nid, node] : graph.getNodes()) {
                    if (node && node->numOutputPorts() > 0) {
                        fallbackOut = nid;
                    }
                }
            }
            if (fallbackOut != audio::INVALID_NODE_ID) {
                graph.setOutputNode(fallbackOut, 0);
            }
        }

        graph.compile();
    }

    // If graph has no nodes, set up the standard synthesis graph so audio is never silent
    if (graph.getNodeCount() == 0) {
        auto tb = std::make_shared<audio::Tb303Node>("Tb303");
        auto delay = std::make_shared<audio::DelayNode>("AcidEcho");
        delay->setDelayTimeMs(125.0f); delay->setFeedback(0.35f); delay->setDryWet(0.30f);
        auto tbStrip = std::make_shared<audio::GainNode>("Track1_Gain");
        auto drums808 = std::make_shared<audio::DrumKitNode>("Drums808");
        auto drum808Strip = std::make_shared<audio::GainNode>("Track2_Gain");
        auto drums909 = std::make_shared<audio::DrumKitNode>("Drums909");
        auto drum909Strip = std::make_shared<audio::GainNode>("Track3_Gain");
        auto dx7 = std::make_shared<audio::PolySynthNode>("Dx7Rhodes");
        auto dx7Strip = std::make_shared<audio::GainNode>("Track4_Gain");
        auto piano = std::make_shared<audio::PolySynthNode>("ConcertGrand");
        auto pianoStrip = std::make_shared<audio::GainNode>("Track5_Gain");
        auto masterGain = std::make_shared<audio::GainNode>("MasterOut");
        masterGain->setVolume(0.85f);

        audio::NodeId tbId = graph.addNode(tb);
        audio::NodeId dlId = graph.addNode(delay);
        audio::NodeId tbG = graph.addNode(tbStrip);
        audio::NodeId d8Id = graph.addNode(drums808);
        audio::NodeId d8G = graph.addNode(drum808Strip);
        audio::NodeId d9Id = graph.addNode(drums909);
        audio::NodeId d9G = graph.addNode(drum909Strip);
        audio::NodeId dxId = graph.addNode(dx7);
        audio::NodeId dxG = graph.addNode(dx7Strip);
        audio::NodeId pId = graph.addNode(piano);
        audio::NodeId pG = graph.addNode(pianoStrip);
        audio::NodeId mId = graph.addNode(masterGain);

        graph.connect(tbId, 0, dlId, 0); graph.connect(dlId, 0, tbG, 0); graph.connect(tbG, 0, mId, 0);
        graph.connect(d8Id, 0, d8G, 0); graph.connect(d8G, 0, mId, 0);
        graph.connect(d9Id, 0, d9G, 0); graph.connect(d9G, 0, mId, 0);
        graph.connect(dxId, 0, dxG, 0); graph.connect(dxG, 0, mId, 0);
        graph.connect(pId, 0, pG, 0); graph.connect(pG, 0, mId, 0);
        graph.setOutputNode(mId, 0);
        graph.compile();
    }

    // Parse title
    static const std::regex titleRegex(R"(title\s*=\s*["']([^"']*)["'])");
    std::smatch match;
    if (std::regex_search(eatsScript, match, titleRegex)) {
        outTitle = match[1].str();
    }

    // Parse BPM
    static const std::regex bpmRegex(R"(bpm\s*=\s*([\d\.]+))");
    if (std::regex_search(eatsScript, match, bpmRegex)) {
        outBpm = std::stod(match[1].str());
    }

    // Parse Swing
    static const std::regex swingRegex(R"(swing\s*=\s*([\d\.]+))");
    if (std::regex_search(eatsScript, match, swingRegex)) {
        outSwing = std::stod(match[1].str());
    }

    sequencer.setBpm(outBpm);
    sequencer.setSwing(outSwing);
    sequencer.clearPatterns();

    // Find all pattern blocks (e.g. "Pattern A", "Pattern B", "Pattern 1")
    std::vector<std::pair<std::string, size_t>> patternsFound;
    static const std::regex tracksBlockRegex(R"(tracks\s*=\s*\{)");
    std::sregex_iterator patIt(eatsScript.begin(), eatsScript.end(), tracksBlockRegex);
    std::sregex_iterator end;

    for (; patIt != end; ++patIt) {
        size_t trkBlockPos = patIt->position();
        std::string pName = "Pattern " + std::to_string(patternsFound.size() + 1);
        size_t lookbackStart = (trkBlockPos >= 400) ? (trkBlockPos - 400) : 0;
        std::string lookback = eatsScript.substr(lookbackStart, trkBlockPos - lookbackStart);
        static const std::regex patNameRegex(R"(name\s*=\s*["']([^"']*)["'])");
        std::sregex_iterator pnIt(lookback.begin(), lookback.end(), patNameRegex);
        std::string lastPName;
        for (; pnIt != end; ++pnIt) {
            lastPName = (*pnIt)[1].str();
        }
        if (!lastPName.empty()) {
            pName = lastPName;
        }
        patternsFound.emplace_back(pName, trkBlockPos);
    }

    if (patternsFound.empty()) {
        patternsFound.emplace_back("Pattern 1", 0);
    }

    for (size_t pIdx = 0; pIdx < patternsFound.size(); ++pIdx) {
        size_t patIdx = sequencer.addPattern(patternsFound[pIdx].first);
        auto& pat = sequencer.getPattern(patIdx);
        pat.tracks.clear();

        size_t blockStart = patternsFound[pIdx].second;
        size_t blockEnd = (pIdx + 1 < patternsFound.size()) ? patternsFound[pIdx + 1].second : eatsScript.size();
        std::string patternSection = eatsScript.substr(blockStart, blockEnd - blockStart);

        // Identify track blocks within patternSection
        static const std::regex idRegex(R"(\bid\s*=\s*["']([^"']+)["'])");
        std::sregex_iterator idIt(patternSection.begin(), patternSection.end(), idRegex);
        std::vector<size_t> trackOffsets;

        for (; idIt != end; ++idIt) {
            std::string idVal = (*idIt)[1].str();
            // Filter out clips, fx, and step note IDs
            if (idVal.rfind("clip", 0) == 0 || idVal.rfind("c_", 0) == 0) continue;
            if (idVal.rfind("fx", 0) == 0) continue;
            if (idVal.rfind("n_", 0) == 0 || idVal.rfind("s_", 0) == 0 || idVal.rfind("h_", 0) == 0) continue;

            size_t idPos = idIt->position();
            size_t checkLen = std::min<size_t>(350, patternSection.size() - idPos);
            std::string preview = patternSection.substr(idPos, checkLen);

            // Clips contain 'trackId'
            if (preview.find("trackId") != std::string::npos) continue;
            // Notes contain 'pitch' and 'startStep'
            if (preview.find("pitch") != std::string::npos && preview.find("startStep") != std::string::npos) continue;
            // Patterns contain 'lengthSteps' or 'tracks =' or have pattern IDs like 'p0', 'pat_0'
            if (preview.find("lengthSteps") != std::string::npos || preview.find("tracks =") != std::string::npos) continue;
            static const std::regex patIdRegex(R"(^p(?:at_)?\d+$)");
            if (std::regex_match(idVal, patIdRegex)) continue;
            // Tracks must have name
            static const std::regex hasNameRegex(R"(name\s*=\s*["'][^"']+["'])");
            if (!std::regex_search(preview, hasNameRegex)) continue;

            trackOffsets.push_back(idPos);
        }

        for (size_t i = 0; i < trackOffsets.size(); ++i) {
            size_t start = trackOffsets[i];
            size_t endPos = (i + 1 < trackOffsets.size()) ? trackOffsets[i + 1] : patternSection.size();
            std::string trkChunk = patternSection.substr(start, endPos - start);

            std::string trkName = "Track " + std::to_string(i + 1);
            static const std::regex trkNameRegex(R"(name\s*=\s*["']([^"']*)["'])");
            if (std::regex_search(trkChunk, match, trkNameRegex)) {
                trkName = match[1].str();
            }

            uint32_t targetNodeId = 0;
            static const std::regex nodeIdRegex(R"(targetNodeId\s*=\s*(\d+))");
            if (std::regex_search(trkChunk, match, nodeIdRegex)) {
                targetNodeId = static_cast<uint32_t>(std::stoul(match[1].str()));
            }

            // Remap old node ID or match by instrument keywords to modular synth graph
            if (oldToNewId.count(targetNodeId)) {
                targetNodeId = oldToNewId[targetNodeId];
            } else if (graph.getNodeCount() > 0) {
                std::string lowerTrk = trkName;
                std::transform(lowerTrk.begin(), lowerTrk.end(), lowerTrk.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
                audio::NodeId matchedId = 0;

                for (const auto& [nid, node] : graph.getNodes()) {
                    if (!node) continue;
                    std::string lowerNode = node->getName();
                    std::transform(lowerNode.begin(), lowerNode.end(), lowerNode.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

                    if ((lowerTrk.find("303") != std::string::npos || lowerTrk.find("acid") != std::string::npos || lowerTrk.find("bass") != std::string::npos) &&
                        (lowerNode.find("303") != std::string::npos || lowerNode.find("acid") != std::string::npos)) {
                        matchedId = nid; break;
                    } else if ((lowerTrk.find("kick") != std::string::npos || lowerTrk.find("808") != std::string::npos || lowerTrk.find("bd") != std::string::npos) &&
                               lowerNode.find("808") != std::string::npos) {
                        matchedId = nid; break;
                    } else if ((lowerTrk.find("hat") != std::string::npos || lowerTrk.find("cymbal") != std::string::npos || lowerTrk.find("909") != std::string::npos || lowerTrk.find("hh") != std::string::npos) &&
                               lowerNode.find("909") != std::string::npos) {
                        matchedId = nid; break;
                    } else if ((lowerTrk.find("snare") != std::string::npos || lowerTrk.find("clap") != std::string::npos || lowerTrk.find("sd") != std::string::npos) &&
                               (lowerNode.find("808") != std::string::npos || lowerNode.find("909") != std::string::npos)) {
                        matchedId = nid; break;
                    } else if ((lowerTrk.find("rhodes") != std::string::npos || lowerTrk.find("dx") != std::string::npos || lowerTrk.find("ep") != std::string::npos || lowerTrk.find("keys") != std::string::npos) &&
                               (lowerNode.find("rhodes") != std::string::npos || lowerNode.find("dx") != std::string::npos)) {
                        matchedId = nid; break;
                    } else if ((lowerTrk.find("piano") != std::string::npos || lowerTrk.find("grand") != std::string::npos || lowerTrk.find("guitar") != std::string::npos || lowerTrk.find("string") != std::string::npos || lowerTrk.find("lead") != std::string::npos) &&
                               (lowerNode.find("piano") != std::string::npos || lowerNode.find("grand") != std::string::npos)) {
                        matchedId = nid; break;
                    }
                }

                if (matchedId == 0) {
                    // Pick a sound generator node (outputs > 0, inputs == 0)
                    std::vector<audio::NodeId> generators;
                    for (const auto& [nid, node] : graph.getNodes()) {
                        if (node && node->numOutputPorts() > 0 && node->numInputPorts() == 0) {
                            generators.push_back(nid);
                        }
                    }
                    if (!generators.empty()) {
                        matchedId = generators[i % generators.size()];
                    }
                }
                targetNodeId = matchedId;
            }

            sequencer::SequencerTrack trk(trkName, targetNodeId, 16);

            // Volume & Pan
            static const std::regex volRegex(R"(\bvolume\s*=\s*([\d\.]+))");
            if (std::regex_search(trkChunk, match, volRegex)) {
                trk.setVolume(std::stof(match[1].str()));
            }

            static const std::regex panRegex(R"(\bpan\s*=\s*([-\d\.]+))");
            if (std::regex_search(trkChunk, match, panRegex)) {
                trk.setPan(std::stof(match[1].str()));
            }

            // Mute / Solo
            static const std::regex muteRegex(R"(isMuted\s*=\s*(true|false))");
            if (std::regex_search(trkChunk, match, muteRegex)) {
                trk.setMuted(match[1].str() == "true");
            }
            static const std::regex soloRegex(R"(isSoloed\s*=\s*(true|false))");
            if (std::regex_search(trkChunk, match, soloRegex)) {
                trk.setSolo(match[1].str() == "true");
            }

            // EatScript Code / LuaScript Code
            static const std::regex scriptCodeRegex(R"((?:eatScriptCode|luaScriptCode)\s*=\s*\[\[([\s\S]*?)\]\])");
            if (std::regex_search(trkChunk, match, scriptCodeRegex)) {
                std::string code = match[1].str();
                size_t first = code.find_first_not_of(" \t\r\n");
                size_t last = code.find_last_not_of(" \t\r\n");
                if (first != std::string::npos && last != std::string::npos) {
                    trk.setEatscriptCode(code.substr(first, last - first + 1));
                }
            }

            uint32_t maxStep = 16;

            // Format A: steps = { [1] = { pitch = 36, velocity = 0.80, isSlide = false, isAccent = false } }
            static const std::regex stepRegex(R"(\[(\d+)\]\s*=\s*\{([^}]*)\})");
            std::sregex_iterator stepIt(trkChunk.begin(), trkChunk.end(), stepRegex);
            for (; stepIt != end; ++stepIt) {
                uint32_t sIdx = static_cast<uint32_t>(std::stoul((*stepIt)[1].str()));
                if (sIdx > 0 && sIdx <= sequencer::MAX_STEPS_PER_TRACK) {
                    std::string stepBody = (*stepIt)[2].str();
                    sequencer::StepData sd;
                    sd.active = true;

                    static const std::regex pRegex(R"(pitch\s*=\s*(\d+))");
                    static const std::regex vRegex(R"(velocity\s*=\s*([\d\.]+))");
                    static const std::regex slRegex(R"(isSlide\s*=\s*(true|false))");
                    static const std::regex acRegex(R"(isAccent\s*=\s*(true|false))");

                    std::smatch sm;
                    if (std::regex_search(stepBody, sm, pRegex)) sd.note = static_cast<uint8_t>(std::stoi(sm[1].str()));
                    if (std::regex_search(stepBody, sm, vRegex)) sd.velocity = std::stof(sm[1].str());
                    if (std::regex_search(stepBody, sm, slRegex)) sd.slide = (sm[1].str() == "true");
                    if (std::regex_search(stepBody, sm, acRegex)) sd.accent = (sm[1].str() == "true");

                    trk.setStep(sIdx - 1, sd);
                    if (sIdx > maxStep) maxStep = sIdx;
                }
            }

            // Format B: notes = { { ... startStep = ... } } (in track notes and clip notes)
            static const std::regex noteRegex(R"(\{[^{}]*\bstartStep\s*=\s*([\d\.]+)[^{}]*\})");
            std::sregex_iterator noteIt(trkChunk.begin(), trkChunk.end(), noteRegex);
            for (; noteIt != end; ++noteIt) {
                std::string noteBody = noteIt->str();

                static const std::regex pitchRx(R"(\bpitch\s*=\s*(\d+))");
                static const std::regex stepRx(R"(\bstartStep\s*=\s*([\d\.]+))");
                static const std::regex durRx(R"(\bdurationSteps\s*=\s*([\d\.]+))");
                static const std::regex velRx(R"(\bvelocity\s*=\s*([\d\.]+))");
                static const std::regex slRx(R"(\bisSlide\s*=\s*(true|false))");
                static const std::regex acRx(R"(\bisAccent\s*=\s*(true|false))");

                std::smatch smP, smS;
                if (std::regex_search(noteBody, smP, pitchRx) && std::regex_search(noteBody, smS, stepRx)) {
                    uint8_t noteNum = static_cast<uint8_t>(std::stoi(smP[1].str()));
                    float startStep = std::stof(smS[1].str());
                    uint32_t sIdx = static_cast<uint32_t>(std::round(startStep));

                    if (sIdx < sequencer::MAX_STEPS_PER_TRACK) {
                        float dur = 1.0f;
                        float vel = 0.8f;
                        bool slide = false;
                        bool accent = false;

                        std::smatch smOther;
                        if (std::regex_search(noteBody, smOther, durRx)) dur = std::stof(smOther[1].str());
                        if (std::regex_search(noteBody, smOther, velRx)) vel = std::stof(smOther[1].str());
                        if (std::regex_search(noteBody, smOther, slRx)) slide = (smOther[1].str() == "true");
                        if (std::regex_search(noteBody, smOther, acRx)) accent = (smOther[1].str() == "true");

                        auto& existingStep = trk.getStep(sIdx);
                        if (existingStep.active) {
                            if (existingStep.note != noteNum) {
                                if (std::find(existingStep.extraNotes.begin(), existingStep.extraNotes.end(), noteNum) == existingStep.extraNotes.end()) {
                                    existingStep.extraNotes.push_back(noteNum);
                                }
                            }
                        } else {
                            sequencer::StepData sd;
                            sd.active = true;
                            sd.note = noteNum;
                            sd.velocity = std::clamp(vel, 0.05f, 1.0f);
                            sd.slide = slide;
                            sd.accent = accent;
                            sd.gateLength = (dur >= 1.0f) ? 0.95f : std::clamp(dur, 0.1f, 0.95f);
                            trk.setStep(sIdx, sd);
                        }
                        if (sIdx + 1 > maxStep) maxStep = sIdx + 1;
                    }
                }
            }

            if (maxStep > 16) {
                uint32_t alignedSteps = std::min(static_cast<uint32_t>(sequencer::MAX_STEPS_PER_TRACK), ((maxStep + 15) / 16) * 16);
                trk.setNumSteps(alignedSteps);
            } else {
                trk.setNumSteps(16);
            }

            pat.tracks.push_back(std::move(trk));
        }
    }

    if (sequencer.getNumPatterns() > 0) {
        sequencer.setActivePatternIndex(0);
    }

    return true;
}

} // namespace eatsbits::project
