#include "eatsbits/project/eats_serializer.hpp"
#include "eatsbits/audio/graph/nodes/tb303_node.hpp"
#include "eatsbits/audio/graph/nodes/drum_kit_node.hpp"
#include "eatsbits/audio/graph/nodes/poly_synth_node.hpp"
#include "eatsbits/audio/graph/nodes/biquad_node.hpp"
#include "eatsbits/audio/graph/nodes/delay_node.hpp"
#include "eatsbits/audio/graph/nodes/gain_node.hpp"
#include "eatsbits/audio/graph/nodes/eatscript_node.hpp"
#include <sstream>
#include <iomanip>
#include <regex>
#include <map>

namespace eatsbits::project {

static std::string escapeStr(const std::string& str) {
    std::string out;
    for (char c : str) {
        if (c == '"') out += "\\\"";
        else if (c == '\\') out += "\\\\";
        else out += c;
    }
    return out;
}

bool EatsProjectSerializer::isEatsScriptFormat(const std::string& content) noexcept {
    if (content.find("eatsbeats.song") != std::string::npos) return true;
    if (content.find("# Eatsbeats Song File:") != std::string::npos) return true;
    if (content.find("return eatsbeats.song") != std::string::npos) return true;
    return false;
}

std::string EatsProjectSerializer::serialize(
    const audio::AudioGraph& graph,
    const sequencer::StepSequencer& sequencer,
    const std::string& title,
    double bpm,
    double swing) {

    std::ostringstream ss;
    ss << std::fixed << std::setprecision(2);

    ss << "# Eatsbeats Song File: \"" << escapeStr(title) << "\"\n";
    ss << "# Generated by Eatsbeats DAW\n\n";
    ss << "return eatsbeats.song {\n";
    ss << "  version = \"1.0\",\n";

    // Meta
    ss << "  meta = {\n";
    ss << "    title = \"" << escapeStr(title) << "\",\n";
    ss << "    bpm = " << bpm << ",\n";
    ss << "    swing = " << swing << ",\n";
    ss << "    masterVolume = 0.85,\n";
    ss << "    isSongMode = false,\n";
    ss << "    isLooping = false,\n";
    ss << "  },\n\n";

    // Graph
    if (graph.getNodeCount() > 0) {
        ss << "  graph = {\n";
        ss << "    outputNodeId = " << graph.getOutputNodeId() << ",\n";
        ss << "    nodes = {\n";
        for (const auto& [id, node] : graph.getNodes()) {
            if (!node) continue;
            ss << "      {\n";
            ss << "        id = " << id << ",\n";
            ss << "        name = \"" << escapeStr(node->getName()) << "\",\n";

            if (auto* tb = dynamic_cast<audio::Tb303Node*>(node.get())) {
                ss << "        type = \"tb303\",\n";
            } else if (auto* dk = dynamic_cast<audio::DrumKitNode*>(node.get())) {
                ss << "        type = \"drum_kit\",\n";
            } else if (auto* ps = dynamic_cast<audio::PolySynthNode*>(node.get())) {
                ss << "        type = \"poly_synth\",\n";
            } else if (auto* bq = dynamic_cast<audio::BiquadNode*>(node.get())) {
                ss << "        type = \"biquad\",\n";
            } else if (auto* dl = dynamic_cast<audio::DelayNode*>(node.get())) {
                ss << "        type = \"delay\",\n";
                ss << "        delayTimeMs = " << dl->getDelayTimeMs() << ",\n";
                ss << "        feedback = " << dl->getFeedback() << ",\n";
                ss << "        dryWet = " << dl->getDryWet() << ",\n";
            } else if (auto* gn = dynamic_cast<audio::GainNode*>(node.get())) {
                ss << "        type = \"gain\",\n";
                ss << "        volume = " << gn->getVolume() << ",\n";
                ss << "        pan = " << gn->getPan() << ",\n";
                ss << "        muted = " << (gn->isMuted() ? "true" : "false") << ",\n";
            } else if (auto* es = dynamic_cast<audio::EatscriptNode*>(node.get())) {
                ss << "        type = \"eatscript\",\n";
                ss << "        script = [[\n" << es->getScript() << "\n        ]],\n";
            } else {
                ss << "        type = \"generic\",\n";
            }
            ss << "      },\n";
        }
        ss << "    },\n";

        ss << "    connections = {\n";
        for (const auto& conn : graph.getConnections()) {
            ss << "      { srcNode = " << conn.srcNode << ", srcPort = " << conn.srcPort
               << ", dstNode = " << conn.dstNode << ", dstPort = " << conn.dstPort << " },\n";
        }
        ss << "    },\n";
        ss << "  },\n\n";
    }

    // Patterns
    ss << "  patterns = {\n";
    for (size_t p = 0; p < sequencer.getNumPatterns(); ++p) {
        const auto& pat = sequencer.getPattern(p);
        ss << "    {\n";
        ss << "      id = \"pat_" << p << "\",\n";
        ss << "      name = \"" << escapeStr(pat.name) << "\",\n";
        ss << "      lengthSteps = 16,\n";
        ss << "      tracks = {\n";

        for (size_t t = 0; t < pat.tracks.size(); ++t) {
            const auto& track = pat.tracks[t];
            ss << "        {\n";
            ss << "          id = \"trk_" << t << "\",\n";
            ss << "          name = \"" << escapeStr(track.getName()) << "\",\n";
            ss << "          targetNodeId = " << track.getTargetNodeId() << ",\n";
            ss << "          volume = 0.850,\n";
            ss << "          pan = 0.000,\n";
            ss << "          isMuted = " << (track.isMuted() ? "true" : "false") << ",\n";
            ss << "          isSoloed = " << (track.isSolo() ? "true" : "false") << ",\n";

            // Embed Eatscript code
            const std::string& code = track.getEatscriptCode();
            if (!code.empty()) {
                ss << "          eatScriptCode = [[\n" << code << "\n          ]],\n";
            }

            // Steps
            ss << "          steps = {\n";
            for (uint32_t s = 0; s < track.getNumSteps(); ++s) {
                const auto& step = track.getStep(s);
                if (!step.active) continue;

                ss << "            [" << (s + 1) << "] = { ";
                ss << "pitch = " << static_cast<int>(step.note) << ", ";
                ss << "velocity = " << std::setprecision(2) << step.velocity << ", ";
                ss << "isSlide = " << (step.slide ? "true" : "false") << ", ";
                ss << "isAccent = " << (step.accent ? "true" : "false") << " },\n";
            }
            ss << "          },\n";
            ss << "        },\n";
        }

        ss << "      }\n";
        ss << "    },\n";
    }
    ss << "  },\n";
    ss << "}\n";

    return ss.str();
}

bool EatsProjectSerializer::deserialize(
    const std::string& eatsScript,
    audio::AudioGraph& graph,
    sequencer::StepSequencer& sequencer,
    std::string& outTitle,
    double& outBpm,
    double& outSwing) {

    if (!isEatsScriptFormat(eatsScript)) {
        return false;
    }

    outTitle = "Untitled Song";
    outBpm = 135.0;
    outSwing = 0.50;

    // Check for graph block
    size_t graphPos = eatsScript.find("graph = {");
    if (graphPos != std::string::npos) {
        graph.clear();
        std::map<uint32_t, audio::NodeId> oldToNewId;

        // Output Node Id
        static const std::regex outNodeRegex(R"(outputNodeId\s*=\s*(\d+))");
        std::smatch outMatch;
        uint32_t targetOutputId = audio::INVALID_NODE_ID;
        if (std::regex_search(eatsScript, outMatch, outNodeRegex)) {
            targetOutputId = static_cast<uint32_t>(std::stoul(outMatch[1].str()));
        }

        // Nodes block
        size_t nodesStart = eatsScript.find("nodes = {", graphPos);
        size_t connsStart = eatsScript.find("connections = {", graphPos);
        if (nodesStart != std::string::npos && connsStart != std::string::npos) {
            std::string nodesChunk = eatsScript.substr(nodesStart, connsStart - nodesStart);
            static const std::regex nodeStartRegex(R"(id\s*=\s*(\d+))");
            std::sregex_iterator nit(nodesChunk.begin(), nodesChunk.end(), nodeStartRegex);
            std::sregex_iterator nEnd;
            std::vector<size_t> nOffsets;
            for (; nit != nEnd; ++nit) {
                nOffsets.push_back(nit->position());
            }

            for (size_t i = 0; i < nOffsets.size(); ++i) {
                size_t nStart = nOffsets[i];
                size_t nEndPos = (i + 1 < nOffsets.size()) ? nOffsets[i + 1] : nodesChunk.size();
                std::string nStr = nodesChunk.substr(nStart, nEndPos - nStart);

                uint32_t oldId = 0;
                std::smatch nm;
                if (std::regex_search(nStr, nm, nodeStartRegex)) {
                    oldId = static_cast<uint32_t>(std::stoul(nm[1].str()));
                }

                std::string nName = "Node";
                static const std::regex nNameRegex(R"(name\s*=\s*["']([^"']*)["'])");
                if (std::regex_search(nStr, nm, nNameRegex)) {
                    nName = nm[1].str();
                }

                std::string nType = "generic";
                static const std::regex nTypeRegex(R"(type\s*=\s*["']([^"']*)["'])");
                if (std::regex_search(nStr, nm, nTypeRegex)) {
                    nType = nm[1].str();
                }

                std::shared_ptr<audio::GraphNode> newNode;
                if (nType == "tb303") {
                    newNode = std::make_shared<audio::Tb303Node>(nName.empty() ? "TB303" : nName);
                } else if (nType == "drum_kit") {
                    newNode = std::make_shared<audio::DrumKitNode>(nName.empty() ? "DrumKit" : nName);
                } else if (nType == "poly_synth") {
                    newNode = std::make_shared<audio::PolySynthNode>(nName.empty() ? "PolySynth" : nName);
                } else if (nType == "biquad") {
                    newNode = std::make_shared<audio::BiquadNode>(nName.empty() ? "Filter" : nName);
                } else if (nType == "delay") {
                    auto dl = std::make_shared<audio::DelayNode>(nName.empty() ? "Delay" : nName);
                    static const std::regex dtRegex(R"(delayTimeMs\s*=\s*([\d\.]+))");
                    static const std::regex fbRegex(R"(feedback\s*=\s*([\d\.]+))");
                    static const std::regex dwRegex(R"(dryWet\s*=\s*([\d\.]+))");
                    if (std::regex_search(nStr, nm, dtRegex)) dl->setDelayTimeMs(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, fbRegex)) dl->setFeedback(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, dwRegex)) dl->setDryWet(std::stof(nm[1].str()));
                    newNode = dl;
                } else if (nType == "gain") {
                    auto gn = std::make_shared<audio::GainNode>(nName.empty() ? "Gain" : nName);
                    static const std::regex volRegex(R"(volume\s*=\s*([\d\.]+))");
                    static const std::regex panRegex(R"(pan\s*=\s*([-\d\.]+))");
                    static const std::regex muteRegex(R"(muted\s*=\s*(true|false))");
                    if (std::regex_search(nStr, nm, volRegex)) gn->setVolume(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, panRegex)) gn->setPan(std::stof(nm[1].str()));
                    if (std::regex_search(nStr, nm, muteRegex)) gn->setMute(nm[1].str() == "true");
                    newNode = gn;
                } else if (nType == "eatscript") {
                    auto es = std::make_shared<audio::EatscriptNode>(nName.empty() ? "Eatscript" : nName);
                    static const std::regex scriptRegex(R"(script\s*=\s*\[\[([\s\S]*?)\]\])");
                    if (std::regex_search(nStr, nm, scriptRegex)) {
                        std::string sc = nm[1].str();
                        size_t f = sc.find_first_not_of(" \t\r\n");
                        size_t l = sc.find_last_not_of(" \t\r\n");
                        if (f != std::string::npos && l != std::string::npos) {
                            es->setScript(sc.substr(f, l - f + 1));
                        }
                    }
                    newNode = es;
                }

                if (newNode) {
                    audio::NodeId newId = graph.addNode(newNode);
                    oldToNewId[oldId] = newId;
                }
            }
        }

        // Connections block
        if (connsStart != std::string::npos) {
            std::string connChunk = eatsScript.substr(connsStart);
            static const std::regex connRegex(R"(\{\s*srcNode\s*=\s*(\d+),\s*srcPort\s*=\s*(\d+),\s*dstNode\s*=\s*(\d+),\s*dstPort\s*=\s*(\d+)\s*\})");
            std::sregex_iterator cit(connChunk.begin(), connChunk.end(), connRegex);
            std::sregex_iterator cEnd;
            for (; cit != cEnd; ++cit) {
                uint32_t oldSrc = static_cast<uint32_t>(std::stoul((*cit)[1].str()));
                uint32_t srcPort = static_cast<uint32_t>(std::stoul((*cit)[2].str()));
                uint32_t oldDst = static_cast<uint32_t>(std::stoul((*cit)[3].str()));
                uint32_t dstPort = static_cast<uint32_t>(std::stoul((*cit)[4].str()));

                if (oldToNewId.count(oldSrc) && oldToNewId.count(oldDst)) {
                    graph.connect(oldToNewId[oldSrc], srcPort, oldToNewId[oldDst], dstPort);
                }
            }
        }

        if (targetOutputId != audio::INVALID_NODE_ID && oldToNewId.count(targetOutputId)) {
            graph.setOutputNode(oldToNewId[targetOutputId], 0);
        }

        graph.compile();
    }

    // Parse title
    static const std::regex titleRegex(R"(title\s*=\s*["']([^"']*)["'])");
    std::smatch match;
    if (std::regex_search(eatsScript, match, titleRegex)) {
        outTitle = match[1].str();
    }

    // Parse BPM
    static const std::regex bpmRegex(R"(bpm\s*=\s*([\d\.]+))");
    if (std::regex_search(eatsScript, match, bpmRegex)) {
        outBpm = std::stod(match[1].str());
    }

    // Parse Swing
    static const std::regex swingRegex(R"(swing\s*=\s*([\d\.]+))");
    if (std::regex_search(eatsScript, match, swingRegex)) {
        outSwing = std::stod(match[1].str());
    }

    sequencer.setBpm(outBpm);
    sequencer.setSwing(outSwing);
    sequencer.clearPatterns();

    // Find tracks block
    size_t patIdx = sequencer.addPattern("Pattern 1");
    auto& pat = sequencer.getPattern(patIdx);
    pat.tracks.clear();

    // Match each track block: { id = "trk_..." ... }
    static const std::regex trackStartRegex(R"(id\s*=\s*["']trk_(\d+)["'])");
    std::sregex_iterator it(eatsScript.begin(), eatsScript.end(), trackStartRegex);
    std::sregex_iterator end;

    std::vector<size_t> trackOffsets;
    for (; it != end; ++it) {
        trackOffsets.push_back(it->position());
    }

    for (size_t i = 0; i < trackOffsets.size(); ++i) {
        size_t start = trackOffsets[i];
        size_t endPos = (i + 1 < trackOffsets.size()) ? trackOffsets[i + 1] : eatsScript.size();
        std::string trkChunk = eatsScript.substr(start, endPos - start);

        std::string trkName = "Track";
        static const std::regex trkNameRegex(R"(name\s*=\s*["']([^"']*)["'])");
        if (std::regex_search(trkChunk, match, trkNameRegex)) {
            trkName = match[1].str();
        }

        uint32_t targetNodeId = 0;
        static const std::regex nodeIdRegex(R"(targetNodeId\s*=\s*(\d+))");
        if (std::regex_search(trkChunk, match, nodeIdRegex)) {
            targetNodeId = static_cast<uint32_t>(std::stoul(match[1].str()));
        }

        sequencer::SequencerTrack trk(trkName, targetNodeId, 16);

        // Mute / Solo
        static const std::regex muteRegex(R"(isMuted\s*=\s*(true|false))");
        if (std::regex_search(trkChunk, match, muteRegex)) {
            trk.setMuted(match[1].str() == "true");
        }
        static const std::regex soloRegex(R"(isSoloed\s*=\s*(true|false))");
        if (std::regex_search(trkChunk, match, soloRegex)) {
            trk.setSolo(match[1].str() == "true");
        }

        // EatScript Code
        static const std::regex scriptCodeRegex(R"(eatScriptCode\s*=\s*\[\[([\s\S]*?)\]\])");
        if (std::regex_search(trkChunk, match, scriptCodeRegex)) {
            std::string code = match[1].str();
            // Trim leading/trailing whitespace
            size_t first = code.find_first_not_of(" \t\r\n");
            size_t last = code.find_last_not_of(" \t\r\n");
            if (first != std::string::npos && last != std::string::npos) {
                trk.setEatscriptCode(code.substr(first, last - first + 1));
            }
        }

        // Steps: [1] = { pitch = 36, velocity = 0.80, isSlide = false, isAccent = false }
        static const std::regex stepRegex(R"(\[(\d+)\]\s*=\s*\{([^}]*)\})");
        std::sregex_iterator stepIt(trkChunk.begin(), trkChunk.end(), stepRegex);
        for (; stepIt != end; ++stepIt) {
            uint32_t sIdx = static_cast<uint32_t>(std::stoul((*stepIt)[1].str()));
            if (sIdx > 0 && sIdx <= 64) {
                std::string stepBody = (*stepIt)[2].str();
                sequencer::StepData sd;
                sd.active = true;

                static const std::regex pRegex(R"(pitch\s*=\s*(\d+))");
                static const std::regex vRegex(R"(velocity\s*=\s*([\d\.]+))");
                static const std::regex slRegex(R"(isSlide\s*=\s*(true|false))");
                static const std::regex acRegex(R"(isAccent\s*=\s*(true|false))");

                std::smatch sm;
                if (std::regex_search(stepBody, sm, pRegex)) sd.note = static_cast<uint8_t>(std::stoi(sm[1].str()));
                if (std::regex_search(stepBody, sm, vRegex)) sd.velocity = std::stof(sm[1].str());
                if (std::regex_search(stepBody, sm, slRegex)) sd.slide = (sm[1].str() == "true");
                if (std::regex_search(stepBody, sm, acRegex)) sd.accent = (sm[1].str() == "true");

                trk.setStep(sIdx - 1, sd);
            }
        }

        pat.tracks.push_back(std::move(trk));
    }

    return true;
}

} // namespace eatsbits::project
