#ifndef EATS_PROCEDURAL_PIANO_ENGINE_HPP
#define EATS_PROCEDURAL_PIANO_ENGINE_HPP

#include <cstdint>
#include <string>
#include <vector>
#include "../theory/chord_model.hpp"
#include "../sequencer/step_sequencer.hpp"
#include "../ui/views/arranger_view.hpp"

namespace eatsbits::procgen {

/// Individual note generated by the procedural piano engine.
struct PianoNote {
    uint8_t pitch{60};
    double startBeat{0.0};       // Position in beats (0.0 = bar 0 beat 1)
    double durationBeats{1.0};   // Duration in beats
    float velocity{0.75f};
    bool isLeftHand{false};      // Left hand (bass / foundation) vs Right hand (chords / melody)
    bool isArp{false};
};

/// Stylistic execution for harmonic piano accompaniment.
enum class PianoStyle {
    NeoSoul,       // Syncopated lush chords with warm 9ths/11ths and subtle strum rubato
    JazzBallad,    // Rootless open voicings, gentle comping, expressive dynamics
    PopStrum,      // Driving 8th/16th acoustic piano rhythm with octave bass
    Classical,     // Alberti bass left hand with cantabile voice leading
    Arpeggiated    // Continuous cascading broken chord arpeggios
};

[[nodiscard]] const char* getPianoStyleName(PianoStyle style) noexcept;
[[nodiscard]] PianoStyle parsePianoStyle(const std::string& str) noexcept;

/// Parameters for procedural piano generation.
struct PianoPatternParams {
    std::vector<theory::ChordEvent> chords;
    PianoStyle style{PianoStyle::NeoSoul};
    int bars{4};
    double humanize{0.20};
    double strumSpreadBeats{0.035}; // ~20-30ms strum spread in musical beats
    bool addBassOctaves{true};
    uint32_t seed{101};
};

/**
 * Procedural Piano Composition & Voice-Leading Engine.
 * Generates harmonically sound piano accompaniments, smooth voice leading across
 * chord changes, jazz voicings, strum spreads, and arpeggios.
 */
class ProceduralPianoEngine {
public:
    [[nodiscard]] static const std::vector<std::string>& getAvailableStyles();

    /// Generates piano notes from harmonic chords using voice-leading algorithms.
    [[nodiscard]] static std::vector<PianoNote> generatePattern(const PianoPatternParams& params);

    /// Populates an active SequencerTrack with generated piano notes.
    static void populateSequencerTrack(sequencer::SequencerTrack& track, const PianoPatternParams& params);

    /// Populates an ArrangerTimelineClip with generated piano notes.
    static void populateArrangerClip(ui::ArrangerTimelineClip& clip, const PianoPatternParams& params);

    /// Computes voice leading for a 4-part chord voicing to minimize voice movement from previous chord.
    [[nodiscard]] static std::vector<int> computeVoiceLeading(
        const std::vector<int>& pitchClasses,
        const std::vector<int>& previousVoicing,
        int minMidi = 60,
        int maxMidi = 84
    );
};

} // namespace eatsbits::procgen

#endif // EATS_PROCEDURAL_PIANO_ENGINE_HPP
