#ifndef EATS_PROCEDURAL_DRUM_ENGINE_HPP
#define EATS_PROCEDURAL_DRUM_ENGINE_HPP

#include <cstdint>
#include <string>
#include <vector>
#include "../sequencer/step_sequencer.hpp"
#include "../ui/views/arranger_view.hpp"

namespace eatsbits::procgen {

/// Note event generated by the procedural drum engine mapped to General MIDI drums.
struct DrumNote {
    uint8_t pitch{36};          // GM MIDI Pitch (e.g. 36 = Kick, 38 = Snare, 42 = Closed Hat)
    double startStep{0.0};      // 16th-step position (floating point for micro-timing swing/jitter)
    double durationSteps{1.0};
    float velocity{0.85f};
};

/// Parameters guiding the procedural drum groove generation.
struct DrumPatternParams {
    std::string style{"House / Disco (4-on-Floor)"};
    int bars{4};                 // 1 to 16 bars
    double density{0.70};        // Pattern density
    double swing{0.20};          // 16th-note swing factor (0.0 to 1.0)
    double ghostProb{0.25};      // Snare ghost note probability
    double fillDensity{0.35};    // Tom / snare fill probability on turnaround bars
    double humanize{0.25};       // Timing and velocity micro-variations
    uint32_t seed{42};
};

/**
 * Procedural Drum & Polyrhythmic Groove Engine.
 * Generates dynamic, humanized drum grooves mapped to GM Standard Drum Kit (Notes 35–81)
 * or 808/909 drum machines, featuring micro-timing swing, ghost notes, and turnaround fills.
 */
class ProceduralDrumEngine {
public:
    [[nodiscard]] static const std::vector<std::string>& getAvailableStyles();

    /// Generates notes for the specified drum groove.
    [[nodiscard]] static std::vector<DrumNote> generatePattern(const DrumPatternParams& params);

    /// Populates an active SequencerTrack with generated drum steps.
    static void populateSequencerTrack(sequencer::SequencerTrack& track, const DrumPatternParams& params);

    /// Populates an ArrangerTimelineClip with generated drum notes.
    static void populateArrangerClip(ui::ArrangerTimelineClip& clip, const DrumPatternParams& params);
};

} // namespace eatsbits::procgen

#endif // EATS_PROCEDURAL_DRUM_ENGINE_HPP
