#ifndef EATS_PROCEDURAL_ACID_ENGINE_HPP
#define EATS_PROCEDURAL_ACID_ENGINE_HPP

#include <cstdint>
#include <string>
#include <vector>
#include "../sequencer/step_sequencer.hpp"
#include "../ui/views/arranger_view.hpp"

namespace eatsbits::procgen {

/// Note event generated by the acid engine conforming to authentic TB-303 rules.
struct AcidNote {
    uint8_t pitch{36};
    double startStep{0.0};
    double durationSteps{1.0};
    float velocity{0.68f};
    bool isSlide{false};
    bool isAccent{false};
};

/// Parameters guiding the procedural TB-303 algorithmic sequence generator.
struct AcidPatternParams {
    std::string style{"Classic Chicago Acid (1987)"};
    std::string scaleName{"Minor Pentatonic"};
    int rootPitchClass{0};       // 0 = C
    int baseMidiOctave{36};      // MIDI 36 = C2 (classic 303 base)
    int bars{2};                 // 1 to 8 bars
    double density{0.75};        // Note gate density
    double tieProb{0.30};        // Probability of tying consecutive steps
    double slideProb{0.40};      // Probability of portamento glissando
    double accentProb{0.35};     // Probability of resonant accent hit
    int octaveRange{2};          // 1, 2, or 3 octaves
    uint32_t seed{303};
};

/**
 * Procedural TB-303 Acid Sequence Generator.
 * Implements authentic 16-step Roland TB-303 sequencing rules:
 * - Constant-rate 60ms portamento glissando (+0.05 step overlap).
 * - Tied notes without re-triggering ADSR envelopes.
 * - Dynamic accents (0.95 vs 0.68 velocity).
 * - Turnaround fills and syncopated octave leaps.
 */
class ProceduralAcidEngine {
public:
    [[nodiscard]] static const std::vector<std::string>& getAvailableStyles();
    [[nodiscard]] static const std::vector<std::string>& getAvailableScales();
    [[nodiscard]] static std::vector<int> getScaleIntervals(const std::string& scaleName);

    /// Generates a vector of notes conforming to 303 hardware articulation.
    [[nodiscard]] static std::vector<AcidNote> generatePattern(const AcidPatternParams& params);

    /// Populates an active SequencerTrack with generated steps.
    static void populateSequencerTrack(sequencer::SequencerTrack& track, const AcidPatternParams& params);

    /// Populates an ArrangerTimelineClip with generated notes.
    static void populateArrangerClip(ui::ArrangerTimelineClip& clip, const AcidPatternParams& params);
};

} // namespace eatsbits::procgen

#endif // EATS_PROCEDURAL_ACID_ENGINE_HPP
